### ISSUE TITLE
[Question] How to ARP spoof the whole LAN?

### ISSUE THREAD

**Issue by mritd** [irai/packet#13]
I'm writing a transparent proxy tool that I want to automatically proxy client IPs from my entire LAN to my "virtual gateway" device.

I don't know much about the ARP protocol, and I have successfully implemented "forced proxy for a single host" through the example; I want to further automate it to all hosts;

I can think of iterating over all hosts via `Session.HostTable` and executing the `StartHunt` method; but I don't know how to deal with new devices joining the LAN.

Can you provide some suggestions and examples?

**Comment by mritd** [comment]
Sorry I think I figured it out... just set the IP to 0.0.0.0 and the Mac to FF:FF:FF:FF.

**Comment by irai** [comment]
Good you figured a way to do it however your best option is to use the online notification handler and StartHunt for all new Hosts as you get notified. Have a look at the notification example here: https://github.com/irai/packet/tree/main/examples/hosts

You need a notification handler like: 
```
go func() {
		for {
			notification := <-yourSession.C
			switch notification.Online {
			case true:
				fmt.Printf("is online: %s\n", notification)
                                yourArpHandler.StartHunt(notification.Addr)
			default:
				fmt.Printf("is offline: %s\n", notification)
                                yourArpHandler.StopHunt(notification.Addr)
			}
			s.PrintTable()
		}
	}()
```
